// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIVAxLR6KGBohr2XC3NC5AVasVJ2CvR4',
    appId: '1:405758882255:web:e30a5ef986465a8f99a2ba',
    messagingSenderId: '405758882255',
    projectId: 'chatbot-46baf',
    authDomain: 'chatbot-46baf.firebaseapp.com',
    storageBucket: 'chatbot-46baf.firebasestorage.app',
    measurementId: 'G-GK3HRQJ8WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIalLdXl1o4LKj8Hb4-zlvU5jIbJPFEzo',
    appId: '1:405758882255:android:168c1b759295904f99a2ba',
    messagingSenderId: '405758882255',
    projectId: 'chatbot-46baf',
    storageBucket: 'chatbot-46baf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtmCpA5-aFQ4JWbhZcIXATl7fuvcJWTOc',
    appId: '1:405758882255:ios:32db8da064fc371799a2ba',
    messagingSenderId: '405758882255',
    projectId: 'chatbot-46baf',
    storageBucket: 'chatbot-46baf.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

}